### ISSUE TITLE
Userscript: incorrect text on the "View image" button

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [bijij/ViewImage#162]
Instead of "View image" it says "Search by image".
Userscript version 2.0.1.1

**Comment by bijij** [comment]
Should be fixed. Hopefully.

**Comment by nbmrjuhneibkr** [comment]
No, it's not fixed.
https://gist.github.com/bijij/58cc8cfc859331e4cf80210528a7b255/revisions
Userscript has not been updated since September 2018.

**Comment by nbmrjuhneibkr** [comment]
Seems to be fixed now. Thanks.
