### ISSUE TITLE
"VIew image" button appears, but doesn't do anything

### ISSUE THREAD

**Issue by Reonu** [bijij/ViewImage#259]
**Describe the bug**
The view image button is there, but it doesn't do anything

**To Reproduce**
Click the button

**Expected behavior**
It should open the image

**System Information**
 - Browser: Firefox
 - Version: 101.0.1

**Additional context**
Example URL: https://www.google.com/search?q=among%20us%20crewmate&tbm=isch&tbs=ic:trans&client=firefox-b-d&hl=es&sa=X&ved=0CAMQpwVqFwoTCPi95rKFwfgCFQAAAAAdAAAAABAC&biw=2048&bih=991#imgrc=dd4ojpkkzW4IGM

**Comment by ner00** [comment]
Works fine for me though.

**Comment by Reonu** [comment]
I swear it doesn't work for me :(

**Comment by GoblinKisser** [comment]
Having the same problem. Tried those steps, still not working for me.

**Comment by ner00** [comment]
Not sure then. Have also tried in a refreshed version of Firefox and also worked fine there. Does it show an URL at all when you hover the button?

Just to cover all bases, can you report the version of the extension (as specified in the browser's extensions section)?

Also, open Dev Tools and check the console for any errors related to the extension when loading the Google Images page.

Lastly, inspect the "View Image" button element and share a screenshot or the html code for it.

**Comment by GoblinKisser** [comment]
Version is 3.6.5.

For errors, I have this:
![image](https://user-images.githubusercontent.com/40656593/175270453-1fe3f0e5-f789-4982-a361-7b2711aff202.png)

When inspecting, I get this:
![image](https://user-images.githubusercontent.com/40656593/175270723-4812004b-8b7c-4c3a-8425-8fba10c0c24d.png)

![image](https://user-images.githubusercontent.com/40656593/175270797-09ade2e2-9475-4026-9bc9-b13772659414.png)

**Comment by ner00** [comment]
The top image with the errors might be a good clue that something is being blocked, although the fact that the button appears in the first place doesn't seem to indicate that it's this particular extension. I may be wrong, but it might be blocking multiple extensions that could be the reason or not - try disabling all other extensions temporarily aside from "View Image" to see if that makes any difference.

As for the inspection, I would have hoped that it showed the inspection of the actual button, which is not the case in the screenshots above, it would look more like this:
![firefox_ye2XHFF3pg](https://user-images.githubusercontent.com/2269603/175273169-11f9e9c3-edcd-4cfa-a439-1943f813e7f7.png)

Anyway, I think @bijij is probably better equipped to advise on what could be the cause here.

**Comment by GoblinKisser** [comment]
Oh sorry I missed that other question. There is a url appearing when I hover. Also, for the inspection, I clicked inspect over the View Image button and got what I posted so I don't know what to do to get the html you posted. Disabling all but view image did make the button work again though, so I'm going to re-enable them one by one to see if it's a specific one blocking it.

**Comment by Reonu** [comment]
Since apparently it's uBlock Origin breaking it, I've reported the issue to the uBlock Origin devs

**Comment by ner00** [comment]
Well, glad you at least made some progress, it's just very weird since I also have uBlock Origins installed and do not have this issue. Are you using the default uBlock lists or some more aggressive blocking lists?

Btw, this is mine on Google Images page:

![TlEu31Uf4O](https://user-images.githubusercontent.com/2269603/175285093-fbab2674-726d-4ddd-a793-5acde917cb83.png)

**Comment by GoblinKisser** [comment]
Here's how it looks for me.
![image](https://user-images.githubusercontent.com/40656593/175288168-700bdd6c-449d-4c10-80da-d57a00bd430b.png)

I do have some extra stuff besides the default, although I've had them selected for so long I don't remember what is and isn't default anymore, and this issue only just started happening to me the other day.

**Comment by ner00** [comment]
Fair enough. Anyway, the two shouldn't be interfering with each other. My guess is that it is possible that uBlock or a third-party list they use may have updated some target objects which are being prevented to be injected by View Image. It's just a guess, but doesn't really solve anything.

**Comment by Reonu** [comment]
The "uBlock Annoyances" filter which was the one causing the issue has been updated and this has been fixed. Click the button to purge all caches, then update your filters, it will work again.

**Comment by nicolaasjan** [comment]
Well, this issue is closed as completed now, but I still have the issue that multiple clicks on the button are needed.
Do I have to open a new issue for this?

**Comment by Reonu** [comment]
I guess? For me it works first try everytime now
