### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by nicolaasjan** [bijij/ViewImage#285]
**Describe the bug**
View Image (v5.1.0) button does not appear any more.

**To Reproduce**
Go to:
https://www.google.com/search?hl=en&q=cats&udm=2
and click on  a random image.

**Expected behavior**
View Image button should appear.

**Screenshot**

![screenshor_20240615](https://github.com/bijij/ViewImage/assets/14093220/79e949ce-92d2-4d6e-a842-650a6f82300f)

**System Information**
Firefox 127.0
&
Chromium-dev 128.0.6539.0

**Additional context**
[Userscript](https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3/raw/viewimage.user.js) from @ner00 doesn't work either (v3.7.0.14)

[**Edit**]
Works again after switching to the updated script (v3.7.0.15) from @ner00 😀️
(see revision [here](https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3/revisions#diff-493df5a0606726dc30efd49da04fa768ffacc44cd25558dbf9883958094c5c47R7))

**Comment by MaskMan191** [comment]
I'm experiencing the same thing. No "View Image" button appears, just share and save.

**Comment by foreachthing** [comment]
It's right there:
![image](https://github.com/bijij/ViewImage/assets/10420187/7d645682-fadb-4f11-b422-bd0e5cd7cb98)

View Image (v5.1.0), Brave Browser (_1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit)_) on Windows 11.

**Comment by ner00** [comment]
I think some people are getting a new class name instead of the one embedded in the code, namely `.tvh9oe`, which in my case now either uses `.EIehLd` or `.fHE6De`.

**Comment by nicolaasjan** [comment]
> I think some people are getting a new class name instead of the one embedded in the code, namely `.tvh9oe`, which in my case now either uses `.EIehLd` or `.fHE6De`.
> 
> https://github.com/bijij/ViewImage/blob/200827af5fbcfdcf74971cb4350d2fc92ac7b465/js/content-script.js#L34C11-L34C43

I can't find `EIehLd` or `fHE6De` in the source code of the page.
And I don't know exactly where to look what is used with the inspector...

**Comment by ner00** [comment]
> I can't find `EIehLd` or `fHE6De` in the source code of the page.
> And I don't know exactly where to look what is used with the inspector...

Try to locate yourself based on the screenshot below (search term was `cats`)

![image](https://github.com/bijij/ViewImage/assets/2269603/0b5192f1-ce90-4699-97b3-8af3720b1a2d)

**Comment by foreachthing** [comment]
I just noticed, that the extension "[Google Images Restored](https://chrome.google.com/webstore/detail/google-images-restored/ncndcebmkibkhopclfdjfacgfholcghi/)" was active. Without it, there is no link in Brave either.

**Comment by ner00** [comment]
> there is no link in Brave either.

This is because Google is constantly doing A/B implementations, where they change something and push that to a group of users and not another. Usually if you are logged in you should have the same issue across browsers, but those A/B tests are pushed based on different variables which I can only guess (cookies, preferences, browser, region, primary language, etc.). Unfortunately this type of thing has been happening pretty often in the past couple years.

**Comment by nicolaasjan** [comment]
Thanks!
It works again using your updated script.
Now the extension needs to be updated as well.

**Comment by ner00** [comment]
> It works again using your updated script.

Cool.
If possible, please edit your opening post where you say it doesn't work (it may be chronologically confusing).

**Comment by Reonu** [comment]
Will the extension itself be updated to account for this?

**Comment by bijij** [comment]
Hi All, I've submitted a new version 5.2 which should hopefully resolve this issue.

**Comment by nicolaasjan** [comment]
Thanks!

**Comment by MaskMan191** [comment]
> Hi All, I've submitted a new version 5.2 which should hopefully resolve this issue.

Any ETA on when it will be updated for Firefox? Not sure why the topic author closed the issue when the issue is still present.

**Comment by nicolaasjan** [comment]
> Not sure why the topic author closed the issue when the issue is still present.

It is fixed on Chromium. 🙂
I will reopen when for some reason the coming update won't work on Firefox.

**Comment by bijij** [comment]
> Any ETA on when it will be updated for Firefox? Not sure why the topic author closed the issue when the issue is still present.

Still waiting on Mozilla to approve the update unfortunately, hopefully sooner than later.

**Comment by MaskMan191** [comment]
> > Any ETA on when it will be updated for Firefox? Not sure why the topic author closed the issue when the issue is still present.
> 
> Still waiting on Mozilla to approve the update unfortunately, hopefully sooner than later.

Did Mozilla just never approve this? It still isn't working.

**Comment by nicolaasjan** [comment]
For some reason version 5.2.0 stopped working again on Firefox. 🤔
The [userscript](https://gist.github.com/ner00/ec9ae47e202b8e99f19be44a5af6baf3/raw/viewimage.user.js) from @ner00 still works.

**Comment by AydenHitcher** [comment]
Not working since Mozilla Update. Or maybe google changes anything. I hope for a fix <3

**Comment by ner00** [comment]
https://github.com/bijij/ViewImage/issues/242#issuecomment-1139210812
